name: Test

on:
  push:
    branches:
      - main # Reemplaza con tu rama principal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Puedes cambiar la versión de Node.js si es necesario

      - name: Install dependencies
        run: npm install # O yarn install si usas yarn

      - name: Run test
        run: npm test #
